### ISSUE TITLE
Allow multiple instances, and/or multiple sprite projects open at once

### ISSUE THREAD

**Issue by fafafrei** [piskelapp/piskel#526] opened 2016-08-16 03:18 UTC
It would be nice to have something like a "create new piskel" button on the desktop app that either opens up a new instance of Piskel desktop or opens the new Piskel in a new tab.  The web version basically already does this, but I see no similar functionality in the desktop app.

**Comment by juliandescottes** [comment] 2017-06-02 22:52
That's actually a duplicate of #271 
And that should be fixed now.

**Closed by juliandescottes** 2017-06-02 22:52 UTC
Labels: feature, offline applications
