### ISSUE TITLE
Preview Windows and Frames Bug

### ISSUE THREAD

**Issue by PoptartPresident** [piskelapp/piskel#779] opened 2018-02-07 02:23 UTC
**Bug description:**
Whenever I am on a sprite, I see that the previews or frames are way too zoomed in, and have no way to zoom out. They are already at "full" preview even though this wasn't how it was previously. When you click on the "preview in popup" window, or you click on another frame, the actual sprites are fine. It's just the preview visuals that are too "zoomed in". 
This can be slightly frustrating because I will be trying to figure out which parts of the pictures I need to zoom into to edit them, but I can't determine that easily due to the unusual presentation of the previews.

**Steps to reproduce the bug**
1. go to piskelapp.com
2. select your sprite
3. look at the preview windows or frames

**Environment details**
* browser (or offline application version):

**Sprite details**
Has been happening since Monday, February 5th of 2018.
Only witnessed on larger sprites/designs.

**Screenshots:**
![example 1](https://user-images.githubusercontent.com/28955267/35895041-4ff8b532-0b7b-11e8-99b5-fe06f203824b.png)
![example 1 pt 2](https://user-images.githubusercontent.com/28955267/35895045-539383ca-0b7b-11e8-94bc-63bb1f016090.png)
![example 2](https://user-images.githubusercontent.com/28955267/35895051-5a4db8c0-0b7b-11e8-8567-a9dacdfdf354.png)
![example 2 pt 2](https://user-images.githubusercontent.com/28955267/35895057-5d6bd726-0b7b-11e8-9a0d-7921e22b5f69.png)
![example 3](https://user-images.githubusercontent.com/28955267/35895060-608b7470-0b7b-11e8-822f-cdc0c6413f9c.png)
![example 3 pt 2](https://user-images.githubusercontent.com/28955267/35895062-63119742-0b7b-11e8-9ef3-9525c4916772.png)

**Comment by juliandescottes** [comment] 2018-02-07 07:07
Thanks for reporting the issue!

Looks like this is a Chrome only issue. And I think it is caused by the following bug tracked on Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=807636

Basically for Piskel it means that when I scale down a canvas context to "zoom out" to preview, it ignores my scale. I'm a bit surprised/scared that this doesn't have more impact in Piskel, as I scale and draw canvases in a lot of spots. All things considered, if it's just the preview window it's not too bad.

They suggest to disable HW acceleration for Canvas to "fix" the issue, however it might slow down Piskel a lot if you do so. Looks like they hope to have a fix released for Chrome 64 next week.

I'll see if can implement a workaround in the meantime, but no guarantees.

**Comment by juliandescottes** [comment] 2018-02-14 08:42
Fix has been released in Chrome Version 64.0.3282.167 which I just got today. Closing. Thanks for reporting!!

**Closed by juliandescottes** 2018-02-14 08:42 UTC
Labels: bug
