### ISSUE TITLE
The downloaded version of piskel keeps crashing when ever I try to open the program.

### ISSUE THREAD

**Issue by Toppingss** [piskelapp/piskel#797] opened 2018-04-05 00:34 UTC
Bug description
So I try to access piskel through the program that I downloaded through chrome and what happens is
 a black screen pops up that says loading at the top and after a short period of time, the whole program just crashes.
![37804650-7bf9779a-2df2-11e8-9fce-6df6948c100d](https://user-images.githubusercontent.com/37645060/38341632-672f3c6e-382e-11e8-977d-409833b04b12.gif)
![37804683-a3666e00-2df2-11e8-82eb-e9cfbb1dfe73](https://user-images.githubusercontent.com/37645060/38341637-6f303378-382e-11e8-8ed5-1da7c5a11fd1.png)

(this template is intended for bug reports, erase it when requesting features/enhancements)

### Steps to reproduce the bug
1. go to piskelapp.com
2. select a tool
3. ...

### Environment details
* operating system:
* browser (or offline application version):

### Sprite details
* number of frames:
* sprite resolution:
* session duration:

Feel free to include a screenshot of the bug, a .piskel file of the sprite or anything else that can help us investigate.

**Comment by juliandescottes** [comment] 2018-04-05 13:05
This is a duplicate of #791

**Closed by juliandescottes** 2018-04-05 13:05 UTC

**Comment by juliandescottes** [comment] 2018-04-05 17:54
The existing issue was not ignored, it is still open.

**Comment by Toppingss** [comment] 2018-04-05 18:00
Well it has been 14 days with out a resoponce. I got asked to send a screen
shot and I did. Plus I send a gif showing exactly whats happening and 14
days later I get nothing
