### ISSUE TITLE
Why not make Categories so you can organize your sprites.

### ISSUE THREAD

**Issue by CanvasOfficial1** [piskelapp/piskel#810] opened 2018-05-01 21:01 UTC
# hegglet
      This would help so much because after about 300 sprites, it gets hard to find things. This would optimize the amount of time you had to look for things. I don't see any problem with this feature besides creating it.

**Comment by juliandescottes** [comment] 2018-05-01 21:36
Thanks for the request. This is already requested in 
- https://github.com/piskelapp/piskel-website/issues/5
- https://github.com/piskelapp/piskel/issues/773

Closing this one as a duplicate of the issues linked above. For the record, I also don't see any problem with this feature besides creating it :)

**Closed by juliandescottes** 2018-05-01 21:36 UTC
