### ISSUE TITLE
Layer Issues- Layer changes in all frames

### ISSUE THREAD

**Issue by RainyDayMay** [piskelapp/piskel#778] opened 2018-02-05 22:35 UTC
Hi everyone,

Teacher here using Piskel in my high school classroom.  My students are all running into the same issue.  When they alter something on a layer in one frame the layer changes in all frames.  This is very frustrating, is there a way anyone knows of to stop this from happening?

This is my first time using GitHub, any advice would be appreciated.  Thank you!

**Comment by juliandescottes** [comment] 2018-02-05 22:39
Hi @RainyDayMay 

Which browser are you using? I just tried on Chrome and Firefox and can't reproduce the issue.

> When they alter something on a layer in one frame the layer changes in all frames 

Some tools can be applied to all frames when holding SHIFT, does this happen even with the simple Pen tool?

**Comment by juliandescottes** [comment] 2018-02-05 22:56
Or maybe you mean that when you select a layer the previews in the frame list are all updated to display the content of the current layer? This would be by design. 
All frames share the same layers, so when you create a layer, it is added for all frames. When you select a layer, the frame list on the left of the canvas will show the content of the current layer for each frame. Can be surprising at first but when animating (I think) it is useful to see the same layer on all frames at the same time.

If you can provide screenshots and/or a list of steps (create new sprite -> click on add layer -> click on add frame etc...), that would probably clarify the issue for me.

Thanks.

**Comment by juliandescottes** [comment] 2018-03-01 07:48
No answer, closing.

**Closed by juliandescottes** 2018-03-01 07:48 UTC
