### ISSUE TITLE
Feature Request : create new piskel

### ISSUE THREAD

**Issue by unins** [piskelapp/piskel#702] opened 2017-05-31 01:42 UTC
I'm having problem when I'm creating multiple piskel,
I have to restart program or erase all frames to create another one

It would be great if there is "New Project" button

**Comment by juliandescottes** [comment] 2017-06-01 17:51
Thanks for reporting this @unins . 

It looks like a duplicate of #271 . Let's move the conversation there. 
I think it should be really easy to a "new" button in the header.

**Closed by juliandescottes** 2017-06-01 17:51 UTC
