### ISSUE TITLE
Vertical Mirror pen with SHIFT opens browser context menu on Firefox

### ISSUE THREAD

**Issue by AlexHolly** [piskelapp/piskel#327] opened 2015-11-03 23:59 UTC
"Vertical Mirror pen -> shift+right click to delete pixels" opens a browser(Firefox) popup

**Comment by juliandescottes** [comment] 2015-11-05 06:56
Thanks for reporting the issue, I will have a look !

**Comment by captainbrosset** [comment] 2015-11-30 21:44
Reproduced in a reduced test case here:
http://jsbin.com/surebuqoxi/edit?html,css,js,output

- right-click: the context menu does not appear and the background color changes (which indicates that the contextmenu handler was called)
- shift-right-click: the context menu appears and the background color does not change.

So, it looks like on Firefox, the jquery contextmenu handler does not get executed when shift is pressed.
On Chrome however, pressing shift makes no difference.

So this function isn't called when shift is pressed: https://github.com/juliandescottes/piskel/blob/0dff1f7a9ae671e97ded87b1b36c353c8760b1e5/src/js/controller/DrawingController.js#L314

**Comment by captainbrosset** [comment] 2015-11-30 21:45
And it looks like that's not fixable: http://stackoverflow.com/questions/22760677/how-to-disable-mouse-right-click-menu-when-shift-is-being-pressed-in-firefox

**Comment by juliandescottes** [comment] 2015-11-30 22:19
Thanks for the detailed investigation @captainbrosset 

All tools relying on the SHIFT modifier that can be used with the RIGHT mouse button are not using the ALT modifier as of now.

Some ideas : 
1. use ALT instead of SHIFT
2. make ALT and SHIFT redundant
3. use ALT instead of SHIFT on Firefox
4. do nothing

I prefer SHIFT as a default modifier, so I'm a bit reluctant to switch to ALT. It would also be weird for existing users. Doing it only on FF is even worse I guess.

Having ALT as a backup could be ok, but it needs to be discoverable. Tooltip proposal : 
![image](https://cloud.githubusercontent.com/assets/1141550/11486294/8b12ec70-97b8-11e5-875a-2f57673c9aa7.png)
Could be confusing ?

**Comment by AlexHolly** [comment] 2015-11-30 22:24
Okay, I also found this https://bugzilla.mozilla.org/show_bug.cgi?id=692139
I think ALT is also not working I'm getting a popup.

**Comment by juliandescottes** [comment] 2015-11-30 22:28
@AlexHolly : ALT is working on my machine, which OS are you using ?

**Comment by AlexHolly** [comment] 2015-11-30 22:40
OS = Ubuntu 14.04
Mozilla Firefox 42.0

**Comment by juliandescottes** [comment] 2015-11-30 23:24
Thanks !

Ok so for Ubuntu (maybe other distribs ?) ALT+mouse starts moving the windows. Disabling this behavior is not straightforward, and I can't force it from Piskel either (http://askubuntu.com/questions/67518/how-to-disable-window-move-with-alt-left-mouse-button).

This means that ALT modifiers for tools cannot be used on Ubuntu, be it with the LEFT or RIGHT mouse button.

And the behavior with SHIFT is worse than on Windows :
On Windows, the contextmenu appears on mouseup/click (=> your tool action is still processed).
On Ubuntu, the contextmenu fires immediately on mousedown, which makes this totally unusable.

**Comment by juliandescottes** [comment] 2017-06-10 22:01
Closing as won't fix

**Closed by juliandescottes** 2017-06-10 22:01 UTC
Labels: bug
