### ISSUE TITLE
[Feature] Control Cursor with Keyboard

### ISSUE THREAD

**Issue by P-Star7** [piskelapp/piskel#723] opened 2017-07-17 04:15 UTC
Hi! This is pretty much the best open-source pixel software that I've seen. I used to use Paint.NET, but now I have this with more features for animation, and it's open-source! I do miss one feature from PDN, though: moving the cursor with the arrow keys. For whatever reason, having tactile feedback for the pixels seems to help, such as when feeling out a stroke to see how long it should be. My most ideal version of this would be, when your cursor is in the Piskel window, pressing an arrow key moves it one "pixel width", where a "pixel width" is however many screen pixels each "canvas pixel" is. So it moves more pixels over per key-press when zoomed in, and pressing the right arrow 3 times with the mouse held down always makes three pixels no matter the zoom level. Having it be always-on would mean that you can use keyboard movements for all tools, such as pen, stroke, etc. Also, this wasn't in Paint.NET, but having the pixel your keyboard cursor is on light up would be helpful, just as it is when using the mouse. Thanks!

**Comment by Jose-Moreno** [comment] 2017-07-30 19:50
@P-Star7 Hey can you confirm if this proposal is similar or a duplicate of issue #711 ? If it is please close this issue to maintain the repo clean. Also I think it's worth pasting over your comment on how the tool show work over there and tag Julian so he can read it. Thanks :)

**Comment by juliandescottes** [comment] 2017-07-30 19:56
Good point @Jose-Moreno , both issues should probably be merged and as you said we should keep @P-Star7 's comment in the other thread to make sure the information is not lost!

**Comment by juliandescottes** [comment] 2017-08-06 15:18
Closing as duplicate of #711

**Closed by juliandescottes** 2017-08-06 15:18 UTC
